import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/login');
  await page.getByRole('button', { name: 'Sign in with GitHub' }).click();
  await page.getByRole('textbox', { name: 'Username or email address' }).fill('jrmilburn@outlook.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('D!n!who1!');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await page.getByRole('button', { name: '+ New board' }).click();
  await page.getByRole('textbox', { name: 'Board name' }).fill('New Board');
  await page.getByRole('button', { name: 'Create' }).click();
  await page.getByRole('link', { name: 'New Board' }).click();
  await page.getByRole('button', { name: '+' }).first().click();
  await page.locator('div').filter({ hasText: /^To DoDrop cards here\+$/ }).getByPlaceholder('Add card…').click();
  await page.locator('div').filter({ hasText: /^To DoDrop cards here\+$/ }).getByPlaceholder('Add card…').fill('Card 1');
  await page.getByRole('button', { name: '+' }).first().click();
  await page.locator('div').filter({ hasText: /^To DoCard 1\+$/ }).getByPlaceholder('Add card…').click();
  await page.locator('div').filter({ hasText: /^To DoCard 1\+$/ }).getByPlaceholder('Add card…').fill('Card 2');
  await page.getByRole('button', { name: '+' }).first().click();
  await page.locator('div').filter({ hasText: /^DoingDrop cards here\+$/ }).getByPlaceholder('Add card…').click();
  await page.locator('div').filter({ hasText: /^DoingDrop cards here\+$/ }).getByPlaceholder('Add card…').fill('Card 3');
  await page.getByRole('button', { name: '+' }).nth(1).click();
  await page.locator('div').filter({ hasText: /^DoneDrop cards here\+$/ }).getByPlaceholder('Add card…').click();
  await page.locator('div').filter({ hasText: /^DoneDrop cards here\+$/ }).getByPlaceholder('Add card…').fill(' Card 4');
  await page.getByRole('button', { name: '+' }).nth(2).click();
  await page.getByRole('button', { name: '+ Column' }).click();
  await page.getByRole('textbox', { name: 'Column name' }).fill('New Column');
  await page.getByRole('button', { name: 'Create' }).click();
  await page.locator('div').filter({ hasText: /^New Column$/ }).getByRole('button').click();
  await page.getByRole('menuitem', { name: 'Rename' }).click();
  await page.getByRole('textbox').click();
  await page.getByRole('textbox').fill('Commissioned');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Card 4' }).click();
  await page.getByRole('button', { name: 'Card 4' }).click();
  await page.getByRole('button', { name: 'Card 4' }).click();
  await page.getByRole('button', { name: 'Card 3' }).click();
  await page.getByRole('button', { name: 'Card 4' }).click();
  await page.getByRole('button', { name: 'Card 4' }).click();
  await page.getByRole('button', { name: 'Card 2' }).getByRole('button').click();
  await page.getByRole('menuitem', { name: 'Rename' }).click();
  await page.getByRole('textbox').click();
  await page.getByRole('textbox').fill('Code');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Sign Out' }).click();
});